/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2025-05-29 13:52:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import javax.servlet.http.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    // SESSION & CART SETUP
    String username = (String) session.getAttribute("name"); // Use "name" if that's what you're storing in login
if (username == null) {
    response.sendRedirect("login.jsp");
    return;
}

    List<Integer> cart = (List<Integer>) session.getAttribute("cart");
    if (cart == null) {
        cart = new ArrayList<>();
        session.setAttribute("cart", cart);
    }

    // DB CONNECTION
    Class.forName("org.postgresql.Driver");
    Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/java", "postgres", "1234");

    Statement initStmt = conn.createStatement();

    // TABLE CREATION
    initStmt.executeUpdate("CREATE TABLE IF NOT EXISTS category (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL)");
    initStmt.executeUpdate("CREATE TABLE IF NOT EXISTS product (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, price DECIMAL(10,2) NOT NULL, image_url TEXT, category_id INT REFERENCES category(id))");

    // INSERT SAMPLE DATA
    ResultSet checkCat = initStmt.executeQuery("SELECT COUNT(*) FROM category");
    if (checkCat.next() && checkCat.getInt(1) == 0) {
        initStmt.executeUpdate("INSERT INTO category (name) VALUES ('Electronics'), ('Books'), ('Clothing')");
    }
    checkCat.close();

    ResultSet checkProd = initStmt.executeQuery("SELECT COUNT(*) FROM product");
    if (checkProd.next() && checkProd.getInt(1) == 0) {
        initStmt.executeUpdate("INSERT INTO product (name, price, image_url, category_id) VALUES " +
                "('Smartphone', 15000, 'https://via.placeholder.com/150', 1)," +
                "('Java Book', 500, 'https://via.placeholder.com/150', 2)," +
                "('T-Shirt', 350, 'https://via.placeholder.com/150', 3)");
    }
    checkProd.close();
    initStmt.close();

    // ADD TO CART HANDLER
    String addToCartId = request.getParameter("add_to_cart");
    if (addToCartId != null) {
        try {
            int pid = Integer.parseInt(addToCartId);
            cart.add(pid);
            session.setAttribute("cart", cart);
            response.sendRedirect("dashboard.jsp");
            return;
        } catch (NumberFormatException e) {
            // Ignore invalid ID
        }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>ShopHub</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;\n");
      out.write("            background-color: #fafbfc;\n");
      out.write("            color: #2d3748;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Header */\n");
      out.write("        .navbar {\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            padding: 15px 0;\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            z-index: 1000;\n");
      out.write("            border-bottom: 1px solid rgba(45, 55, 72, 0.08);\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .navbar-brand {\n");
      out.write("            color: #2d3748 !important;\n");
      out.write("            font-weight: 800;\n");
      out.write("            font-size: 24px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            letter-spacing: -0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-container-main {\n");
      out.write("            flex: 1;\n");
      out.write("            max-width: 400px;\n");
      out.write("            margin: 0 20px;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-form {\n");
      out.write("            position: relative;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-input {\n");
      out.write("            width: 100%;\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            padding: 10px 16px 10px 40px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            outline: none;\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            color: #2d3748;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-input:focus {\n");
      out.write("            border-color: #ff6b35;\n");
      out.write("            box-shadow: 0 0 0 2px rgba(255, 107, 53, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-icon {\n");
      out.write("            position: absolute;\n");
      out.write("            left: 14px;\n");
      out.write("            top: 50%;\n");
      out.write("            transform: translateY(-50%);\n");
      out.write("            color: #a0aec0;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sort-dropdown {\n");
      out.write("            position: absolute;\n");
      out.write("            right: 10px;\n");
      out.write("            top: 50%;\n");
      out.write("            transform: translateY(-50%);\n");
      out.write("            border: none;\n");
      out.write("            background: transparent;\n");
      out.write("            font-size: 12px;\n");
      out.write("            color: #718096;\n");
      out.write("            max-width: 100px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-tools {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-item {\n");
      out.write("            color: #4a5568;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 500;\n");
      out.write("            position: relative;\n");
      out.write("            padding: 8px 0;\n");
      out.write("            transition: color 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-item:hover {\n");
      out.write("            color: #2d3748;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-item i {\n");
      out.write("            font-size: 16px;\n");
      out.write("            margin-right: 6px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .cart-count {\n");
      out.write("            background-color: #ff6b35;\n");
      out.write("            color: #ffffff;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            padding: 1px 5px;\n");
      out.write("            font-size: 10px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            right: -8px;\n");
      out.write("            min-width: 16px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Profile Popup */\n");
      out.write("        #profilePopup {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 60px;\n");
      out.write("            right: 10px;\n");
      out.write("            width: 250px;\n");
      out.write("            background: #ffffff;\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);\n");
      out.write("            display: none;\n");
      out.write("            z-index: 1000;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #profilePopup.show {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Main Content */\n");
      out.write("        .main-container {\n");
      out.write("            max-width: 1300px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            padding: 80px 20px 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Category Navigation */\n");
      out.write("        .category-nav {\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            padding: 15px 0;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .category-nav a {\n");
      out.write("            color: #4a5568;\n");
      out.write("            text-decoration: none;\n");
      out.write("            padding: 8px 16px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 500;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            margin-right: 12px;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .category-nav a:hover,\n");
      out.write("        .category-nav a.active {\n");
      out.write("            background-color: #ff6b35;\n");
      out.write("            color: #ffffff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Products Section */\n");
      out.write("        .products-section {\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .section-title {\n");
      out.write("            font-size: 24px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("            letter-spacing: -0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));\n");
      out.write("            gap: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-card {\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 12px 24px rgba(0, 0, 0, 0.1);\n");
      out.write("            border-color: #ff6b35;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-image-container {\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("            height: 200px;\n");
      out.write("            background: #f7fafc;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-image {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 200px;\n");
      out.write("            object-fit: contain;\n");
      out.write("            object-position: center;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            margin-bottom: 12px;\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("            border: 1px solid #e9ecef;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-card:hover .product-image {\n");
      out.write("            transform: scale(1.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-info {\n");
      out.write("            padding: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-title {\n");
      out.write("            font-size: 16px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 6px;\n");
      out.write("            line-height: 1.4;\n");
      out.write("            text-decoration: none;\n");
      out.write("            display: -webkit-box;\n");
      out.write("            -webkit-line-clamp: 2;\n");
      out.write("            -webkit-box-orient: vertical;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-title:hover {\n");
      out.write("            color: #ff6b35;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-category {\n");
      out.write("            font-size: 12px;\n");
      out.write("            color: #718096;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-price {\n");
      out.write("            font-size: 18px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-price .currency {\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-add-cart {\n");
      out.write("            background-color: #ff6b35;\n");
      out.write("            border: none;\n");
      out.write("            color: #ffffff;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 10px 16px;\n");
      out.write("            width: 100%;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-add-cart:hover {\n");
      out.write("            background-color: #e55a2b;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Empty State */\n");
      out.write("        .empty-state {\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 60px 20px;\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .empty-state i {\n");
      out.write("            font-size: 48px;\n");
      out.write("            color: #cbd5e0;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .empty-state h4 {\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            font-size: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .empty-state p {\n");
      out.write("            color: #718096;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background-color: #ff6b35;\n");
      out.write("            border: none;\n");
      out.write("            color: #ffffff;\n");
      out.write("            font-weight: 600;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background-color: #e55a2b;\n");
      out.write("            color: #ffffff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive Design */\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .search-container-main {\n");
      out.write("                margin: 0 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .product-grid {\n");
      out.write("                grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));\n");
      out.write("                gap: 16px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .product-image-container {\n");
      out.write("                height: 160px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .product-image {\n");
      out.write("                height: 180px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #profilePopup {\n");
      out.write("                width: 220px;\n");
      out.write("                right: 5px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .category-nav a {\n");
      out.write("                padding: 6px 12px;\n");
      out.write("                margin-right: 8px;\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Color Palette */\n");
      out.write("        .first-color { \n");
      out.write("            background: #303841; \n");
      out.write("        }\n");
      out.write("            \n");
      out.write("        .second-color { \n");
      out.write("            background: #3a4750; \n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .third-color { \n");
      out.write("            background: #00adb5; \n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .fourth-color { \n");
      out.write("            background: #eeeeee; \n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        function toggleProfilePopup() {\n");
      out.write("            var popup = document.getElementById('profilePopup');\n");
      out.write("            popup.classList.toggle('show');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        document.addEventListener('click', function(event) {\n");
      out.write("            var popup = document.getElementById('profilePopup');\n");
      out.write("            var profileBtn = document.getElementById('profileBtn');\n");
      out.write("            if (!popup.contains(event.target) && !profileBtn.contains(event.target)) {\n");
      out.write("                popup.classList.remove('show');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            // Add to cart animation\n");
      out.write("            const addToCartForms = document.querySelectorAll('form[method=\"get\"]');\n");
      out.write("            addToCartForms.forEach(form => {\n");
      out.write("                form.addEventListener('submit', function(e) {\n");
      out.write("                    const button = this.querySelector('button');\n");
      out.write("                    button.innerHTML = '<i class=\"fas fa-spinner fa-spin me-1\"></i>Adding...';\n");
      out.write("                    button.disabled = true;\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- Simplified Header -->\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"d-flex align-items-center justify-content-between w-100\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"dashboard.jsp\">\n");
      out.write("                ShopHub\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <!-- Search Bar -->\n");
      out.write("            <div class=\"search-container-main\">\n");
      out.write("                <form method=\"get\" action=\"dashboard.jsp\" class=\"search-form\">\n");
      out.write("                    <i class=\"fas fa-search search-icon\"></i>\n");
      out.write("                    <input type=\"text\" name=\"search\" class=\"search-input\"\n");
      out.write("                           placeholder=\"Search products\"\n");
      out.write("                           value=\"");
      out.print( request.getParameter("search") != null ? request.getParameter("search") : "" );
      out.write("\">\n");
      out.write("                    <select name=\"sort\" class=\"sort-dropdown\">\n");
      out.write("                        <option value=\"\" ");
      out.print( (request.getParameter("sort") == null) ? "selected" : "" );
      out.write(">Sort</option>\n");
      out.write("                        <option value=\"asc\" ");
      out.print( "asc".equals(request.getParameter("sort")) ? "selected" : "" );
      out.write(">Price: Low to High</option>\n");
      out.write("                        <option value=\"desc\" ");
      out.print( "desc".equals(request.getParameter("sort")) ? "selected" : "" );
      out.write(">Price: High to Low</option>\n");
      out.write("                    </select>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Navigation Tools -->\n");
      out.write("            <div class=\"nav-tools\">\n");
      out.write("                <a href=\"cart.jsp\" class=\"nav-item position-relative\">\n");
      out.write("                    <i class=\"fas fa-shopping-bag\"></i>\n");
      out.write("                    <span class=\"d-none d-md-inline\">Cart</span>\n");
      out.write("                    <span class=\"cart-count\">");
      out.print( cart.size() );
      out.write("</span>\n");
      out.write("                </a>\n");
      out.write("                <a href=\"#\" id=\"profileBtn\" class=\"nav-item\" onclick=\"toggleProfilePopup()\">\n");
      out.write("                    <i class=\"fas fa-user\"></i>\n");
      out.write("                    <span class=\"d-none d-md-inline\">Profile</span>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Profile Popup -->\n");
      out.write("    <div id=\"profilePopup\">\n");
      out.write("        <p><strong>Hello, ");
      out.print( username );
      out.write("!</strong></p>\n");
      out.write("        <form action=\"user.jsp\" method=\"post\" class=\"my-3\">\n");
      out.write("            <button type=\"submit\" class=\"btn btn-outline-primary btn-sm w-100\">\n");
      out.write("                <i class=\"fas fa-user me-2\"></i>My Profile\n");
      out.write("            </button>\n");
      out.write("        </form>\n");
      out.write("        <form action=\"login.jsp\" method=\"post\">\n");
      out.write("            <button type=\"submit\" class=\"btn btn-outline-secondary btn-sm w-100\">\n");
      out.write("                <i class=\"fas fa-sign-out-alt me-2\"></i>Sign Out\n");
      out.write("            </button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<!-- Main Content -->\n");
      out.write("<div class=\"main-container\">\n");
      out.write("    <!-- Category Navigation -->\n");
      out.write("    <div class=\"category-nav\">\n");
      out.write("        <div class=\"text-center\">\n");
      out.write("            <a href=\"dashboard.jsp\" class=\"");
      out.print( request.getParameter("category") == null ? "active" : "" );
      out.write("\">All Categories</a>\n");
      out.write("            ");

                Statement headerCatStmt = conn.createStatement();
                ResultSet headerCats = headerCatStmt.executeQuery("SELECT * FROM category");
                while (headerCats.next()) {
                    String categoryId = headerCats.getString("id");
                    String isActive = categoryId.equals(request.getParameter("category")) ? "active" : "";
            
      out.write("\n");
      out.write("            <a href=\"?category=");
      out.print( categoryId );
      out.write("\" class=\"");
      out.print( isActive );
      out.write('"');
      out.write('>');
      out.print( headerCats.getString("name") );
      out.write("</a>\n");
      out.write("            ");
 }
                headerCats.close();
                headerCatStmt.close();
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Products Section -->\n");
      out.write("    <div class=\"products-section\">\n");
      out.write("        <h2 class=\"section-title\">\n");
      out.write("            ");
      out.print( request.getParameter("search") != null ? "Search Results" : "All Products" );
      out.write("\n");
      out.write("        </h2>\n");
      out.write("\n");
      out.write("        <div class=\"product-grid\">\n");
      out.write("            ");

                String categoryFilter = request.getParameter("category");
                String searchFilter = request.getParameter("search");
                String sortOrder = request.getParameter("sort");

                String sql = "SELECT p.*, c.name AS category_name FROM product p JOIN category c ON p.category_id = c.id WHERE 1=1";

                if (categoryFilter != null && !categoryFilter.trim().isEmpty()) {
                    sql += " AND c.id = " + categoryFilter;
                }
                if (searchFilter != null && !searchFilter.trim().isEmpty()) {
                    sql += " AND LOWER(p.name) LIKE '%" + searchFilter.toLowerCase() + "%'";
                }
                if ("asc".equals(sortOrder)) {
                    sql += " ORDER BY p.price ASC";
                } else if ("desc".equals(sortOrder)) {
                    sql += " ORDER BY p.price DESC";
                }

                Statement prodStmt = conn.createStatement();
                ResultSet products = prodStmt.executeQuery(sql);
                boolean hasProducts = false;
                while (products.next()) {
                    hasProducts = true;
            
      out.write("\n");
      out.write("            <div class=\"product-card\">\n");
      out.write("                <div class=\"product-image-container\">\n");
      out.write("                    <img src=\"");
      out.print( products.getString("image_url") );
      out.write("\"\n");
      out.write("                         class=\"product-image\"\n");
      out.write("                         alt=\"");
      out.print( products.getString("name") );
      out.write("\"\n");
      out.write("                         onerror=\"this.src='https://via.placeholder.com/250x200/f7fafc/718096?text=Product'\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"product-info\">\n");
      out.write("                    <div class=\"product-category\">");
      out.print( products.getString("category_name") );
      out.write("</div>\n");
      out.write("                    <a href=\"#\" class=\"product-title\">");
      out.print( products.getString("name") );
      out.write("</a>\n");
      out.write("                    <div class=\"product-price\">\n");
      out.write("                        <span class=\"currency\">₹</span>");
      out.print( String.format("%.0f", products.getDouble("price")) );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <form method=\"get\">\n");
      out.write("                        <input type=\"hidden\" name=\"add_to_cart\" value=\"");
      out.print( products.getInt("id") );
      out.write("\">\n");
      out.write("                        <button type=\"submit\" class=\"btn-add-cart\">\n");
      out.write("                            Add to Cart\n");
      out.write("                        </button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            ");
 }

                if (!hasProducts) {
            
      out.write("\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"empty-state\">\n");
      out.write("                    <i class=\"fas fa-search\"></i>\n");
      out.write("                    <h4>No products found</h4>\n");
      out.write("                    <p>Try different keywords or browse our categories.</p>\n");
      out.write("                    <a href=\"dashboard.jsp\" class=\"btn btn-primary\">\n");
      out.write("                        View All Products\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            ");

                }
                products.close();
                prodStmt.close();
                conn.close();
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
