/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2025-05-29 07:01:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import javax.servlet.http.*;
import java.util.*;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    String username = (String) session.getAttribute("name");
    if (username == null) {
        response.sendRedirect("login.jsp");
        return;
    }

    String dbURL = "jdbc:postgresql://localhost:5432/java";
    String dbUser = "postgres";
    String dbPass = "1234";

    String email = "", phone = "", address = "", bio = "";

    try {
        Class.forName("org.postgresql.Driver");
        Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPass);

        String sql = "SELECT * FROM register WHERE name = ?";

        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, username);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            email = rs.getString("email");
            phone = rs.getString("phone");
            address = rs.getString("address");
            bio = rs.getString("bio");
        }

        rs.close();
        stmt.close();
        conn.close();
    } catch (Exception e) {
        out.println("<p>Error fetching user data: " + e.getMessage() + "</p>");
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>User Profile - ShopHub</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;\n");
      out.write("            background-color: #fafbfc;\n");
      out.write("            color: #2d3748;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Header */\n");
      out.write("        .navbar {\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            padding: 15px 0;\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            z-index: 1000;\n");
      out.write("            border-bottom: 1px solid rgba(45, 55, 72, 0.08);\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .navbar-brand {\n");
      out.write("            color: #2d3748 !important;\n");
      out.write("            font-weight: 800;\n");
      out.write("            font-size: 24px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            letter-spacing: -0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-tools {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-item {\n");
      out.write("            color: #4a5568;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 500;\n");
      out.write("            position: relative;\n");
      out.write("            padding: 8px 0;\n");
      out.write("            transition: color 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-item:hover {\n");
      out.write("            color: #2d3748;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-item i {\n");
      out.write("            font-size: 16px;\n");
      out.write("            margin-right: 6px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .cart-count {\n");
      out.write("            background-color: #f96d00;\n");
      out.write("            color: #ffffff;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            padding: 1px 5px;\n");
      out.write("            font-size: 10px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            right: -8px;\n");
      out.write("            min-width: 16px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Main Content */\n");
      out.write("        .main-container {\n");
      out.write("            max-width: 1300px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            padding: 80px 20px 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Page Header */\n");
      out.write("        .page-header {\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-title {\n");
      out.write("            font-size: 32px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            letter-spacing: -0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .breadcrumb {\n");
      out.write("            background: none;\n");
      out.write("            padding: 0;\n");
      out.write("            margin: 0;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .breadcrumb a {\n");
      out.write("            color: #718096;\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .breadcrumb a:hover {\n");
      out.write("            color: #f96d00;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .breadcrumb-item.active {\n");
      out.write("            color: #2d3748;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Profile Container */\n");
      out.write("        .profile-container {\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            padding: 32px;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Profile Header */\n");
      out.write("        .profile-header {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-bottom: 32px;\n");
      out.write("            padding-bottom: 24px;\n");
      out.write("            border-bottom: 1px solid #e2e8f0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .profile-avatar {\n");
      out.write("            width: 80px;\n");
      out.write("            height: 80px;\n");
      out.write("            background-color: #f96d00;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin-right: 24px;\n");
      out.write("            color: white;\n");
      out.write("            font-size: 32px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            box-shadow: 0 4px 12px rgba(249, 109, 0, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .profile-info h2 {\n");
      out.write("            font-size: 24px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 4px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .profile-info p {\n");
      out.write("            color: #718096;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Form Sections */\n");
      out.write("        .form-section {\n");
      out.write("            background-color: #f8fafc;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 24px;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("            border: 1px solid #edf2f7;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .section-title {\n");
      out.write("            font-size: 18px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .section-title i {\n");
      out.write("            color: #f96d00;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Form Controls */\n");
      out.write("        .form-label {\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #4a5568;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 8px;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control {\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 12px 16px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            color: #2d3748;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus {\n");
      out.write("            border-color: #f96d00;\n");
      out.write("            box-shadow: 0 0 0 2px rgba(249, 109, 0, 0.1);\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control.readonly-field {\n");
      out.write("            background-color: #f8fafc;\n");
      out.write("            cursor: not-allowed;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-text {\n");
      out.write("            font-size: 12px;\n");
      out.write("            color: #718096;\n");
      out.write("            margin-top: 4px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Buttons */\n");
      out.write("        .button-group {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 16px;\n");
      out.write("            margin-top: 32px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background-color: #f96d00;\n");
      out.write("            border: none;\n");
      out.write("            color: #ffffff;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 12px 24px;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background-color: #e85d00;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 4px 12px rgba(249, 109, 0, 0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            color: #4a5568;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 12px 24px;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background-color: #f8fafc;\n");
      out.write("            border-color: #cbd5e0;\n");
      out.write("            color: #2d3748;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Color Palette */\n");
      out.write("        .first-color { \n");
      out.write("            background: #222831; \n");
      out.write("        }\n");
      out.write("    \n");
      out.write("        .second-color { \n");
      out.write("            background: #393e46; \n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .third-color { \n");
      out.write("            background: #f96d00; \n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fourth-color { \n");
      out.write("            background: #f2f2f2; \n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive Design */\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .profile-container {\n");
      out.write("                padding: 24px 16px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .profile-header {\n");
      out.write("                flex-direction: column;\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .profile-avatar {\n");
      out.write("                margin-right: 0;\n");
      out.write("                margin-bottom: 16px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .button-group {\n");
      out.write("                flex-direction: column;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .btn {\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Animation */\n");
      out.write("        .fade-in {\n");
      out.write("            animation: fadeIn 0.3s ease-in;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes fadeIn {\n");
      out.write("            from { opacity: 0; transform: translateY(10px); }\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Header -->\n");
      out.write("    <nav class=\"navbar\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"d-flex align-items-center justify-content-between w-100\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"dashboard.jsp\">\n");
      out.write("                    ShopHub\n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("                <div class=\"nav-tools\">\n");
      out.write("                    <a href=\"cart.jsp\" class=\"nav-item position-relative\">\n");
      out.write("                        <i class=\"fas fa-shopping-bag\"></i>\n");
      out.write("                        <span class=\"d-none d-md-inline\">Cart</span>\n");
      out.write("                        <span class=\"cart-count\">0</span>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"dashboard.jsp\" class=\"nav-item\">\n");
      out.write("                        <i class=\"fas fa-home\"></i>\n");
      out.write("                        <span class=\"d-none d-md-inline\">Shop</span>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"main-container\">\n");
      out.write("        <!-- Page Header -->\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <nav aria-label=\"breadcrumb\">\n");
      out.write("                <ol class=\"breadcrumb\">\n");
      out.write("                    <li class=\"breadcrumb-item\"><a href=\"dashboard.jsp\">Home</a></li>\n");
      out.write("                    <li class=\"breadcrumb-item active\" aria-current=\"page\">Profile</li>\n");
      out.write("                </ol>\n");
      out.write("            </nav>\n");
      out.write("            <h1 class=\"page-title\">Edit Profile</h1>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Profile Content -->\n");
      out.write("        <div class=\"profile-container fade-in\">\n");
      out.write("            <!-- Profile Header -->\n");
      out.write("            <div class=\"profile-header\">\n");
      out.write("                <div class=\"profile-avatar\">\n");
      out.write("                    ");
      out.print( username.substring(0, 1).toUpperCase() );
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"profile-info\">\n");
      out.write("                    <h2>");
      out.print( username );
      out.write("</h2>\n");
      out.write("                    <p>Update your personal information</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <form action=\"updateProfile.jsp\" method=\"post\">\n");
      out.write("                <!-- Basic Information Section -->\n");
      out.write("                <div class=\"form-section\">\n");
      out.write("                    <h5 class=\"section-title\">\n");
      out.write("                        <i class=\"fas fa-id-card\"></i>\n");
      out.write("                        Basic Information\n");
      out.write("                    </h5>\n");
      out.write("                    \n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\n");
      out.write("                            <label for=\"name\" class=\"form-label\">\n");
      out.write("                                <i class=\"fas fa-user\"></i>\n");
      out.write("                                Username\n");
      out.write("                            </label>\n");
      out.write("                            <input type=\"text\" class=\"form-control readonly-field\" name=\"name\" id=\"name\" value=\"");
      out.print( username );
      out.write("\" readonly />\n");
      out.write("                            <div class=\"form-text\">Username cannot be changed</div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"col-md-6 mb-3\">\n");
      out.write("                            <label for=\"email\" class=\"form-label\">\n");
      out.write("                                <i class=\"fas fa-envelope\"></i>\n");
      out.write("                                Email Address\n");
      out.write("                            </label>\n");
      out.write("                            <input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\" value=\"");
      out.print( email );
      out.write("\" required />\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Contact Information Section -->\n");
      out.write("                <div class=\"form-section\">\n");
      out.write("                    <h5 class=\"section-title\">\n");
      out.write("                        <i class=\"fas fa-address-book\"></i>\n");
      out.write("                        Contact Information\n");
      out.write("                    </h5>\n");
      out.write("                    \n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\n");
      out.write("                            <label for=\"phone\" class=\"form-label\">\n");
      out.write("                                <i class=\"fas fa-phone\"></i>\n");
      out.write("                                Phone Number\n");
      out.write("                            </label>\n");
      out.write("                            <input type=\"tel\" class=\"form-control\" name=\"phone\" id=\"phone\" value=\"");
      out.print( phone );
      out.write("\" required placeholder=\"Enter your phone number\" />\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"col-md-6 mb-3\">\n");
      out.write("                            <label for=\"address\" class=\"form-label\">\n");
      out.write("                                <i class=\"fas fa-map-marker-alt\"></i>\n");
      out.write("                                Address\n");
      out.write("                            </label>\n");
      out.write("                            <textarea class=\"form-control\" name=\"address\" id=\"address\" rows=\"3\" required placeholder=\"Enter your address\">");
      out.print( address );
      out.write("</textarea>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Personal Information Section -->\n");
      out.write("                <div class=\"form-section\">\n");
      out.write("                    <h5 class=\"section-title\">\n");
      out.write("                        <i class=\"fas fa-info-circle\"></i>\n");
      out.write("                        About You\n");
      out.write("                    </h5>\n");
      out.write("                    \n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label for=\"bio\" class=\"form-label\">\n");
      out.write("                            <i class=\"fas fa-pen\"></i>\n");
      out.write("                            Bio\n");
      out.write("                        </label>\n");
      out.write("                        <textarea class=\"form-control\" name=\"bio\" id=\"bio\" rows=\"4\" placeholder=\"Tell us about yourself...\">");
      out.print( bio );
      out.write("</textarea>\n");
      out.write("                        <div class=\"form-text\">Optional: Share a brief description about yourself</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Action Buttons -->\n");
      out.write("                <div class=\"button-group\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\n");
      out.write("                        <i class=\"fas fa-save me-2\"></i>\n");
      out.write("                        Update Profile\n");
      out.write("                    </button>\n");
      out.write("                    \n");
      out.write("                    <a href=\"dashboard.jsp\" class=\"btn btn-secondary\">\n");
      out.write("                        <i class=\"fas fa-arrow-left me-2\"></i>\n");
      out.write("                        Back to Dashboard\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            const form = document.querySelector('form');\n");
      out.write("            const inputs = document.querySelectorAll('.form-control:not(.readonly-field)');\n");
      out.write("            \n");
      out.write("            // Add focus effects\n");
      out.write("            inputs.forEach(input => {\n");
      out.write("                input.addEventListener('focus', function() {\n");
      out.write("                    this.parentElement.style.transform = 'scale(1.01)';\n");
      out.write("                    this.parentElement.style.transition = 'transform 0.2s ease';\n");
      out.write("                });\n");
      out.write("                \n");
      out.write("                input.addEventListener('blur', function() {\n");
      out.write("                    this.parentElement.style.transform = 'scale(1)';\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            // Form validation feedback\n");
      out.write("            form.addEventListener('submit', function(e) {\n");
      out.write("                const submitBtn = this.querySelector('button[type=\"submit\"]');\n");
      out.write("                submitBtn.innerHTML = '<i class=\"fas fa-spinner fa-spin me-2\"></i>Updating...';\n");
      out.write("                submitBtn.disabled = true;\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
