/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2025-06-05 03:52:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.includes;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import javax.servlet.http.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    // Check admin authentication
    Boolean isAdmin = (Boolean) session.getAttribute("is_admin");
    if (isAdmin == null || !isAdmin) {
        response.sendRedirect("login.jsp");
        return;
    }

    String adminUsername = (String) session.getAttribute("admin_username");
    String adminName = (String) session.getAttribute("admin_name");
    if (adminName == null) adminName = adminUsername;

    // Handle logout
    String logout = request.getParameter("logout");
    if ("true".equals(logout)) {
        session.removeAttribute("admin_id");
        session.removeAttribute("admin_username");
        session.removeAttribute("admin_name");
        session.removeAttribute("admin_email");
        session.removeAttribute("admin_role");
        session.removeAttribute("is_admin");
        response.sendRedirect("login.jsp");
        return;
    }

    // Get page title from parameter or default
    String pageTitle = request.getParameter("pageTitle");
    if (pageTitle == null) {
        String currentPage = request.getRequestURI();
        currentPage = currentPage.substring(currentPage.lastIndexOf("/") + 1);
        if (currentPage.contains(".")) {
            currentPage = currentPage.substring(0, currentPage.lastIndexOf("."));
        }
        
        switch(currentPage) {
            case "dashboard": pageTitle = "Dashboard"; break;
            case "productManagement": pageTitle = "Product Management"; break;
            case "orderTracking": pageTitle = "Order Tracking"; break;
            case "categories": pageTitle = "Categories"; break;
            case "productVariants": pageTitle = "Product Variants"; break;
            case "users": pageTitle = "Users"; break;
            case "importExport": pageTitle = "Import/Export"; break;
            case "viewStore": pageTitle = "View Store"; break;
            default: pageTitle = "Admin Dashboard";
        }
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>");
      out.print( pageTitle );
      out.write(" - ShopHub Admin</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;\n");
      out.write("            background-color: #f8fafc;\n");
      out.write("            color: #2d3748;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Admin Header */\n");
      out.write("        .admin-header {\n");
      out.write("            background: linear-gradient(135deg, #2d3748 0%, #4a5568 100%);\n");
      out.write("            color: white;\n");
      out.write("            padding: 15px 0;\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            z-index: 1000;\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .admin-nav {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .admin-brand {\n");
      out.write("            font-size: 24px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .admin-user {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .admin-avatar {\n");
      out.write("            width: 40px;\n");
      out.write("            height: 40px;\n");
      out.write("            background: linear-gradient(135deg, #ff6b35 0%, #f7931e 100%);\n");
      out.write("            border-radius: 50%;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .admin-info h6 {\n");
      out.write("            margin: 0;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .admin-info p {\n");
      out.write("            margin: 0;\n");
      out.write("            font-size: 14px;\n");
      out.write("            opacity: 0.8;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logout-btn {\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\n");
      out.write("            color: white;\n");
      out.write("            padding: 8px 16px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 14px;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logout-btn:hover {\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Sidebar */\n");
      out.write("        .admin-sidebar {\n");
      out.write("            position: fixed;\n");
      out.write("            left: 0;\n");
      out.write("            top: 70px;\n");
      out.write("            width: 250px;\n");
      out.write("            height: calc(100vh - 70px);\n");
      out.write("            background: white;\n");
      out.write("            border-right: 1px solid #e2e8f0;\n");
      out.write("            padding: 20px 0;\n");
      out.write("            overflow-y: auto;\n");
      out.write("            z-index: 999;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-menu {\n");
      out.write("            list-style: none;\n");
      out.write("            padding: 0;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-menu li {\n");
      out.write("            margin-bottom: 4px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-menu a {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 12px 20px;\n");
      out.write("            color: #4a5568;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-menu a:hover,\n");
      out.write("        .sidebar-menu a.active {\n");
      out.write("            background: #f7fafc;\n");
      out.write("            color: #ff6b35;\n");
      out.write("            border-right: 3px solid #ff6b35;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-menu i {\n");
      out.write("            width: 20px;\n");
      out.write("            margin-right: 12px;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Main Content */\n");
      out.write("        .admin-main {\n");
      out.write("            margin-left: 250px;\n");
      out.write("            margin-top: 70px;\n");
      out.write("            padding: 30px;\n");
      out.write("            min-height: calc(100vh - 70px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-header {\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-title {\n");
      out.write("            font-size: 28px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-subtitle {\n");
      out.write("            color: #718096;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Stats Cards */\n");
      out.write("        .stats-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n");
      out.write("            gap: 24px;\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card {\n");
      out.write("            background: white;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 24px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            transition: transform 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-header {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-icon {\n");
      out.write("            width: 48px;\n");
      out.write("            height: 48px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            font-size: 20px;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-icon.users { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }\n");
      out.write("        .stat-icon.orders { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); }\n");
      out.write("        .stat-icon.revenue { background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); }\n");
      out.write("        .stat-icon.products { background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%); }\n");
      out.write("        .stat-icon.categories { background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%); }\n");
      out.write("        .stat-icon.warning { background: linear-gradient(135deg, #fa709a 0%, #fee140 100%); }\n");
      out.write("\n");
      out.write("        .stat-value {\n");
      out.write("            font-size: 28px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 4px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-label {\n");
      out.write("            color: #718096;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Content Sections */\n");
      out.write("        .content-section {\n");
      out.write("            background: white;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 24px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .section-title {\n");
      out.write("            font-size: 20px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Tables */\n");
      out.write("        .admin-table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .admin-table th {\n");
      out.write("            background: #f7fafc;\n");
      out.write("            padding: 12px 16px;\n");
      out.write("            text-align: left;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #4a5568;\n");
      out.write("            border-bottom: 1px solid #e2e8f0;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .admin-table td {\n");
      out.write("            padding: 12px 16px;\n");
      out.write("            border-bottom: 1px solid #e2e8f0;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .admin-table tr:hover {\n");
      out.write("            background: #f7fafc;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-badge {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 4px;\n");
      out.write("            padding: 4px 8px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            font-size: 12px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-processing { background: #fef5e7; color: #d69e2e; }\n");
      out.write("        .status-shipped { background: #e6fffa; color: #319795; }\n");
      out.write("        .status-delivered { background: #f0fff4; color: #38a169; }\n");
      out.write("        .status-pending { background: #edf2f7; color: #718096; }\n");
      out.write("        .status-active { background: #f0fff4; color: #38a169; }\n");
      out.write("        .status-inactive { background: #fed7d7; color: #e53e3e; }\n");
      out.write("\n");
      out.write("        .user-avatar {\n");
      out.write("            width: 32px;\n");
      out.write("            height: 32px;\n");
      out.write("            background: linear-gradient(135deg, #ff6b35 0%, #f7931e 100%);\n");
      out.write("            border-radius: 50%;\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            color: white;\n");
      out.write("            font-weight: 600;\n");
      out.write("            font-size: 12px;\n");
      out.write("            margin-right: 8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Buttons */\n");
      out.write("        .btn-primary {\n");
      out.write("            background: linear-gradient(135deg, #ff6b35 0%, #f7931e 100%);\n");
      out.write("            border: none;\n");
      out.write("            color: white;\n");
      out.write("            font-weight: 600;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 4px 12px rgba(255, 107, 53, 0.3);\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-sm {\n");
      out.write("            padding: 6px 12px;\n");
      out.write("            font-size: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-success {\n");
      out.write("            background: #38a169;\n");
      out.write("            border: none;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-danger {\n");
      out.write("            background: #e53e3e;\n");
      out.write("            border: none;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-warning {\n");
      out.write("            background: #d69e2e;\n");
      out.write("            border: none;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-info {\n");
      out.write("            background: #3182ce;\n");
      out.write("            border: none;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Forms */\n");
      out.write("        .form-control {\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 10px 12px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            transition: border-color 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus {\n");
      out.write("            border-color: #ff6b35;\n");
      out.write("            box-shadow: 0 0 0 2px rgba(255, 107, 53, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Modals */\n");
      out.write("        .modal-content {\n");
      out.write("            border-radius: 12px;\n");
      out.write("            border: none;\n");
      out.write("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-header {\n");
      out.write("            border-bottom: 1px solid #e2e8f0;\n");
      out.write("            padding: 20px 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-body {\n");
      out.write("            padding: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-footer {\n");
      out.write("            border-top: 1px solid #e2e8f0;\n");
      out.write("            padding: 20px 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Alerts */\n");
      out.write("        .alert {\n");
      out.write("            border-radius: 8px;\n");
      out.write("            border: none;\n");
      out.write("            padding: 12px 16px;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .alert-success {\n");
      out.write("            background: #f0fff4;\n");
      out.write("            color: #38a169;\n");
      out.write("            border-left: 4px solid #38a169;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .alert-danger {\n");
      out.write("            background: #fed7d7;\n");
      out.write("            color: #e53e3e;\n");
      out.write("            border-left: 4px solid #e53e3e;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Search and Filter */\n");
      out.write("        .search-filter-bar {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 16px;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-filter-bar .form-control {\n");
      out.write("            min-width: 200px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Action Buttons */\n");
      out.write("        .action-buttons {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Bulk Actions */\n");
      out.write("        .bulk-actions {\n");
      out.write("            background: #f7fafc;\n");
      out.write("            padding: 16px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .bulk-actions.show {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Variants */\n");
      out.write("        .variant-row {\n");
      out.write("            background: #f8f9fa;\n");
      out.write("            padding: 10px;\n");
      out.write("            margin: 5px 0;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            border: 1px solid #dee2e6;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive */\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .admin-sidebar {\n");
      out.write("                transform: translateX(-100%);\n");
      out.write("                transition: transform 0.3s ease;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .admin-sidebar.show {\n");
      out.write("                transform: translateX(0);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .admin-main {\n");
      out.write("                margin-left: 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .stats-grid {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .admin-table {\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .admin-table th,\n");
      out.write("            .admin-table td {\n");
      out.write("                padding: 8px 12px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .search-filter-bar {\n");
      out.write("                flex-direction: column;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .search-filter-bar .form-control {\n");
      out.write("                min-width: auto;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fade-in {\n");
      out.write("            animation: fadeIn 0.5s ease-in;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes fadeIn {\n");
      out.write("            from { opacity: 0; transform: translateY(20px); }\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Admin Header -->\n");
      out.write("    <header class=\"admin-header\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <nav class=\"admin-nav\">\n");
      out.write("                <a href=\"dashboard.jsp\" class=\"admin-brand\">\n");
      out.write("                    <i class=\"fas fa-shield-alt\"></i>\n");
      out.write("                    ShopHub Admin Pro\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <div class=\"admin-user\">\n");
      out.write("                    <div class=\"admin-avatar\">\n");
      out.write("                        ");
      out.print( adminName != null ? adminName.substring(0, 1).toUpperCase() : "A" );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"admin-info\">\n");
      out.write("                        <h6>");
      out.print( adminName != null ? adminName : adminUsername );
      out.write("</h6>\n");
      out.write("                        <p>System Administrator</p>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"?logout=true\" class=\"logout-btn\">\n");
      out.write("                        <i class=\"fas fa-sign-out-alt me-2\"></i>\n");
      out.write("                        Logout\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <!-- Include Sidebar -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/sidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Main Content -->\n");
      out.write("    <main class=\"admin-main\">\n");
      out.write("        <div class=\"fade-in\">\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
